### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by muha-abdulaziz**
add internationalization support using gettext and the arabic translation

### CODE REVIEW

**Comment by orschiro** [comment]
Cool. 

This means we can start to translate green-recorder into other languages? :-)

**Comment by muha-abdulaziz** [comment]
@orschiro  I think yes. but this feature need more testes.
Any way it contains 23 strings. and all of them are small strings. you can translate and test in about 15 minutes.
All you need program like "poedite, Lokalize* or virtaal" (I suggest virtaal). and copy green-recorder.pot to lang.po "like fr.po or en_US.po".
and to test it make this structure of directories "`locale/lang/LC_MESSAGES/`" inside the project directory.
then convert the **lang.po** to **green-recorder.mo** using this command:
`msgfmt lang.po -o green-recorder.mo`
and move green-recorder.mo to locale/lang/LC_MESSAGES/

*note that by installing Lokalize you will download many KDE packages to work.

**Comment by orschiro** [comment]
Thanks!

> All you need program like "poedite, Lokalize* or virtaal" (I suggest virtaal). and copy green-recorder.pot to lang.po "like fr.po or en_US.po"

I forked the repo and searched for `green-recorder.pot`. I couldn't find it. I guess because your pull request hasn't been merged yet, correct?

**Comment by mhsabbagh** [comment]
Thank you for sending this pull request! Unfortunately I am a little bit busy this time, thus, I'll need to wait around 10 days to start checking it. 

@orschiro If it works, we'll create an account on Transifex in order to allow people to translate the software easily. You'd only need to create an account there and translate strings directly. Later, we'll take this translation and merge here.

**Comment by orschiro** [comment]
> If it works, we'll create an account on Transifex in order to allow people to translate the software easily. You'd only need to create an account there and translate strings directly. Later, we'll take this translation and merge here.

Sounds like a great plan. Thank you! :-)

**Comment by mhsabbagh** [comment]
@muha-abdulaziz You haven't edited the setup.py file to include the internationalization files.

**Pull request closed without merging**
