### PR TITLE
Add install guide for ArchLinux package

### PR DESCRIPTION
**Pull request by unixfox**
https://aur.archlinux.org/packages/green-recorder-git/

### CODE REVIEW

**Comment by mhsabbagh** [comment]
Thank you for taking the time to add this :)

**Comment by mhsabbagh** [comment]
Hello.

A new version of the recorder was released adding support for Wayland's GNOME session. However, the new release requires the "pydbus" python module to work. Therefore, I had to remove the guide about installing it on Arch since the installation would results in a broken program: https://github.com/LEW21/pydbus

If you have time, please package the "pydbus" module as a package in AUR and add it a dependancy for Green Recorder, and let me know to add the package here again :)

Thank you.

**Comment by unixfox** [comment]
Dependency added : https://aur.archlinux.org/packages/green-recorder-git/

**Comment by mhsabbagh** [comment]
Thank you! Package added to the page :)

**Pull request merged**
