### PR TITLE
appindiciator fixes

### PR DESCRIPTION
**Pull request by gort818**

### CODE REVIEW

**Comment by mhsabbagh** [comment]
No need for this one. I already worked on another solution for it. It will come with version 2.0 with Wayland's GNOME session support as well :)

**Comment by gort818** [comment]
Oh ok cool, if you need any help let me know! Can you show me a preview of what you are working on? I have yet to work with Wayland it should be fun!

**Comment by mhsabbagh** [comment]
Thank you :) This is it currently: http://i.imgur.com/NhAFER8.png
Unfortunately a lot of these functionalities won't be available with Wayland. Because I'll be using the D-Bus API to connect to the screencasting object which is built in GNOME-Shell itself. However, it will give performance better than the built-in tool itself (because I'll be using V8 instead of V9 by default).

**Comment by mhsabbagh** [comment]
The code is now live :) You can check it if you have a free time.

Sincerely.

**Pull request closed without merging**
